[target.aarch64-apple-darwin]
rustflags = [
    "-L", "/usr/local/mysql/lib",  
    "-l", "mysqlclient",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-L", "/usr/local/mysql/lib",     
    "-l", "mysqlclient",
]
